import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const api = (path, options={}) => fetch(path, {headers:{'Content-Type':'application/json', ...(options.role?{'x-role':options.role}:{})},...options}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);return data});
function App(){
 const [role,setRole]=useState('customer'),[products,setProducts]=useState([]),[cart,setCart]=useState([]),[message,setMessage]=useState(''),[orders,setOrders]=useState([]),[metrics,setMetrics]=useState(null),[health,setHealth]=useState(null);
 const load=async()=>{try{setProducts((await api('/api/products')).products);setHealth(await api('/health'));if(role==='admin')setMetrics(await api('/api/metrics/latency',{role}));if(role==='customer')setOrders((await api('/api/orders?customerId=customer-1')).orders)}catch(e){setMessage(e.message)}};
 useEffect(()=>{load()},[role]);
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.price_cents*x.qty,0),[cart]);
 const add=p=>setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});
 const checkout=async()=>{try{await api('/api/orders',{method:'POST',body:JSON.stringify({customerId:'customer-1',items:cart.map(x=>({productId:x.id,quantity:x.qty}))})});setCart([]);setMessage('Order placed — inventory reserved atomically.');load()}catch(e){setMessage(e.message)}};
 const updateStock=async(p,delta)=>{try{await api(`/api/products/${p.id}/stock`,{method:'PATCH',role,body:JSON.stringify({stock:Math.max(0,p.stock+delta)})});load()}catch(e){setMessage(e.message)}};
 return <main><header><div><span className="mark">L</span><b>LocalLoop</b><small>local delivery, dependable systems</small></div><nav>{['customer','vendor','admin'].map(r=><button className={role===r?'active':''} onClick={()=>{setRole(r);setMessage('')}} key={r}>{r}</button>)}</nav></header>
 <section className="hero"><div><p className="eyebrow">{role.toUpperCase()} WORKSPACE</p><h1>{role==='customer'?'Discover nearby goods.':'Operate with confidence.'}</h1><p>Multi-tier delivery built for clear operations, fast recovery, and correct inventory.</p></div><div className="health"><b>System health</b>{health&&Object.entries(health.tiers).map(([k,v])=><span key={k}><i className={v}/>{k} {v}</span>)}</div></section>
 {message&&<div className="notice">{message}</div>}
 {role==='admin'&&<section className="metrics"><h2>Latency observability</h2>{metrics?<div className="metric-grid"><Metric n="Requests" v={metrics.samples}/><Metric n="p50" v={metrics.p50+' ms'}/><Metric n="p95" v={metrics.p95+' ms'}/><Metric n="p99" v={metrics.p99+' ms'}/></div>:<p>Loading metrics…</p>}<p className="hint">Each request carries a correlation ID and is retained as a structured log in the data tier.</p></section>}
 <section><div className="section-title"><h2>{role==='customer'?'Today on LocalLoop':'Inventory catalog'}</h2><button onClick={load}>Refresh</button></div><div className="products">{products.map(p=><article className="card" key={p.id}><div className="product-art">{p.name[0]}</div><div><h3>{p.name}</h3><p>Vendor: {p.vendor_id}</p><b>₹{(p.price_cents/100).toFixed(2)}</b><span className={p.stock<3?'low':'stock'}>{p.stock} in stock</span></div>{role==='customer'?<button disabled={!p.stock} onClick={()=>add(p)}>Add to basket</button>:<div className="stock-actions"><button onClick={()=>updateStock(p,-1)}>−</button><button onClick={()=>updateStock(p,1)}>+</button></div>}</article>)}</div></section>
 {role==='customer'&&<aside className="basket"><h2>Basket <span>{cart.reduce((s,x)=>s+x.qty,0)}</span></h2>{cart.length?cart.map(x=><p key={x.id}>{x.name} × {x.qty}<b>₹{(x.qty*x.price_cents/100).toFixed(2)}</b></p>):<p className="hint">Your selection will appear here.</p>}<div className="total">Total <b>₹{(total/100).toFixed(2)}</b></div><button className="checkout" disabled={!cart.length} onClick={checkout}>Place secure order</button></aside>}
 {role==='customer'&&orders.length>0&&<section className="orders"><h2>Recent orders</h2>{orders.map(o=><p key={o._id}>{new Date(o.createdAt).toLocaleString()} · <b>{o.status}</b> · ₹{(o.totalCents/100).toFixed(2)}</p>)}</section>}
 </main>}
const Metric=({n,v})=><div><small>{n}</small><strong>{v}</strong></div>; createRoot(document.getElementById('root')).render(<App/>);
